### ISSUE TITLE
Curious about Json Ali spec and pheonix

### ISSUE THREAD

**Issue by pixelhandler** [mxhold/maxwellholder.com#1]
Saw your article https://github.com/mxhold/maxwellholder.com/blob/master/source/blog/2015-06-04-build-a-blog-with-phoenix-and-ember.html.markdown looks really cool. I'm curious if there is anything for pheonix that serializes data for the Json Api 1.0 spec. There is a gem for a rails app JSONAPI Reasources that does a really good job. Pheonix sounds great, just wondering about the new spec for Json api.

**Comment by mxhold** [comment]
Thanks! I haven't seen any libraries like that for Phoenix (which isn't too surprising since its still so new), but if you come across anything let me know!

**Comment by mxhold** [comment]
Ah I just came across [this tweet](https://twitter.com/chris_mccord/status/617784582394486784). Looks like [this project](jeregrine/jsonapi) is in the early stages of development, but is exactly what you're looking for.
