### ISSUE TITLE
web/controllers/post_controller.ex:20: function post_path/3 undefined

### ISSUE THREAD

**Issue by arkadiyk** [mxhold/maxwellholder.com#3]
Probably due to newer version of the framework the `resources "/posts", PostController` should be added to `router.ex` **right after**  executing `mix phoenix.gen.json Post posts title:string body:text`. 

Otherwise any consequent `mix` commands will cause  `web/controllers/post_controller.ex:20: function post_path/3 undefined` error

**Comment by sidwubf** [comment]
+1

**Comment by mxhold** [comment]
Thanks for pointing this out! I think #4 fixed this.
